pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/beegfs_pools/*
      - scripts/beegfspkgs.sh
      - scripts/beegfsm.sh
      - scripts/beegfssd.sh
      - scripts/beegfsmd.sh
      - scripts/beegfsc.sh
      - scripts/beegfs_pools.sh
      - scripts/create_raid0.sh
      - scripts/make_filesystem.sh
    exclude:
      - examples/beegfs_pools/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/beegfs_pools/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/beegfs_pools
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  - name: azhpc.variables.compute_instances
    value: 4
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/beegfs_pools/test.yml
