pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/image/*
      - scripts/create_image.sh
      - scripts/deprovision.sh
    exclude:
      - examples/image/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/image/create_image.json
  # pipeline directory
  azhpc.pipeline_dir: examples/image
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'hpcadmin@builder:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: westeurope
  # azhpc.variables.image_name: foo

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/image/test.yml
