pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/image/*
      - scripts/create_image.sh
      - scripts/deprovision.sh
    exclude:
      - examples/image/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/image/create_image.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/image
  # destination of scripts. Default is hpcuser@headnode:/apps
  - name: azhpc.script_remote_dest
    value: 'hpcadmin@builder:.'

  - name: azhpc.variables_matrix
    value: examples/image/test_matrix.json
# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  # - name: azhpc.variables.variable_name
  #   value: variable_value

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/image/test.yml
