trigger:
  batch: true
  branches:
    include : 
    - azure-pipelines
  paths:
    include:
      - pipelines/*

pool: Default

steps:
  - script: |
      pwd
      ls -al
    displayName: 'Run a multi-line script'
