pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/nvidia/*
      - scripts/update_kernel.sh
      - scripts/wait.sh
      - scripts/install_lis.sh
      - scripts/cuda_drivers.sh
      - scripts/check_gpu.sh
    exclude:
      - examples/nvidia/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/nvidia/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/nvidia
  # destination of scripts. Default is hpcuser@headnode:/apps
  - name: azhpc.script_remote_dest
    value: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  - name: azhpc.variables.location
    value: southcentralus
  #azhpc.variables.vm_type: Standard_NC12s_v3
  - name: azhpc.variables_matrix
    value: examples/nvidia/test_matrix.json
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
#  parameters:
#    extra_steps: ../../../examples/nvidia/test.yml
