pr: none
#schedules:
#- cron: "0 0 * * Sun"
#  displayName: Every Sunday midnight build
#  branches:
#    include:
#    - master
#  always: true

trigger: none
#  batch: true
#  branches:
#    include:
#    - '*'
#  paths:
#    include:
#      - examples/slurm_autoscale/*
#      - pyazhpc/*
#      - examples/slurm_autoscale/scripts/*
#    exclude:
#      - examples/slurm_autoscale/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/slurm_autoscale/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/slurm_autoscale
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcuser@headnode:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  azhpc.variables.location: westeurope
  azhpc.variables.instances: 4
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../apps/openfoam_v8/test.yml
