pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/cc_beegfs/*
    exclude:
      - examples/cc_beegfs/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/cc_beegfs/variables.json
  # pipeline directory
  azhpc.pipeline_dir: examples/cc_beegfs
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: westeurope


# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    pre_steps: ../../../examples/cc_beegfs/init.yml
