pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/glusterfs_data_disks/*
      - scripts/create_raid0.sh
      - scripts/make_filesystem.sh
      - scripts/glusterfs_pkgs.sh
      - scripts/glusterfs_pool.sh
      - scripts/glusterfs_vol.sh
      - scripts/glusterfs_client.sh
    exclude:
      - examples/glusterfs_data_disks/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/glusterfs_data_disks/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/glusterfs_data_disks
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@headnode:.'

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  - name: azhpc.variables.glusterfs_mount
    value: '/glusterfs'
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/glusterfs_data_disks/test.yml
