pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/beeond/*
      - scripts/setupbeeond.sh
      - scripts/startbeeond.sh
    exclude:
      - examples/beeond/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/beeond/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/beeond
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

  - name: azhpc.variables_matrix
    value: examples/beeond/test_matrix.json

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  # - name: azhpc.variables.variable_name
  #   value: variable_value

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  # parameters:
  #   extra_steps: ../../../examples/beeond/test.yml
