pr: none
trigger:
  batch: true
  branches:
    include:
    - master
    - '*'
  paths:
    include:
      - examples/cycleserver_msi/*
      - blocks/cycle-install-server-managed-identity.json
      - blocks/cycle-prereqs-managed-identity.json
      - blocks/cycle-cli-local.json
      - blocks/cycle-cli-jumpbox.json
      - blocks/jumpbox-nfs.json.json
      - blocks/vnet.json
      - scripts/cc_install_managed_identity.sh
    exclude:
      - examples/cycleserver_msi/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/cycleserver_msi/variables.json
  # pipeline directory
  azhpc.pipeline_dir: examples/cycleserver_msi
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: westeurope
  azhpc.variables_matrix: examples/cycleserver_msi/test_matrix.json

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    pre_steps: ../../../examples/cycleserver_msi/init.yml
