pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/lustre_avset/*
      - scripts/lfsrepo.sh
      - scripts/lfspkgs.sh
      - scripts/lfsmaster.sh
      - scripts/lfsoss.sh
      - scripts/lfshsm.sh
      - scripts/lfsclient.sh
      - scripts/lfsimport.sh
      - scripts/lfsloganalytics.sh
    exclude:
      - examples/lustre_avset/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/lustre_avset/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/lustre_avset
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@headnode:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  # azhpc.variables.location: westeurope
  azhpc.variables.compute_instances: 4
  azhpc.variables.low_priority: true
  azhpc.variables.lustre_instances: 4
  # azhpc.variables.la_name: analytics_workspace_name
  # azhpc.variables.la_resourcegroup: analytics_resource_group
  azhpc.variables.log_analytics_lfs_name: lfs
  azhpc.variables.lustre_mount: /lustre
  # azhpc.variables.storage_account: account
  # azhpc.variables.storage_container: container
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/lustre_avset/test.yml
