pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/anf_full/*
      - scripts/replace_nfs_with_anf.sh
    exclude:
      - examples/anf_full/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/anf_full/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/anf_full
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@headnode:.'

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  - name: azhpc.variables.anf_mount
    value: /netapps
  - name: azhpc.variables.compute_instances
    value: 4
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/anf_full/test.yml
