pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/blobfuse/*
      - scripts/blobfuse.sh
    exclude:
      - examples/beeond/readme.md

pool: Default

variables:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  azhpc.config: examples/blobfuse/config.json
  # pipeline directory
  azhpc.pipeline_dir: examples/blobfuse
  # destination of scripts. Default is hpcuser@headnode:/apps
  azhpc.script_remote_dest: 'hpcadmin@headnode:.'

# Add the variables needed in your configuration file
# Uncomment and set values below, or leave commented and thru pipeline variables
  #azhpc.variables.location: southcentralus
  #azhpc.variables.blob_account: account
  #azhpc.variables.blob_container: container
  azhpc.variables.blob_mount: '/blob'

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/blobfuse/test.yml
